### ISSUE TITLE
LEAK: ";/"

### ISSUE THREAD

**Issue by andrebtw** [andrebtw/minishell#23]
Typing ";/" makes a leak.

==30463== 45 bytes in 2 blocks are still reachable in loss record 11 of 61
==30463==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==30463==    by 0x110C98: ft_strjoin_free (ft_strjoin_free.c:48)
==30463==    by 0x10D45D: add_env (env_to_str.c:62)
==30463==    by 0x10D34A: env_to_str (env_to_str.c:31)
==30463==    by 0x10EDB3: exec_cmd (cmds.c:41)
==30463==    by 0x10D732: check_cmd (exec.c:71)
==30463==    by 0x10D667: check_pipe (exec.c:49)
==30463==    by 0x10D5EA: cmd_nb (exec.c:34)
==30463==    by 0x1094B9: loop (main.c:26)
==30463==    by 0x109552: init (main.c:48)
==30463==    by 0x10958C: main (main.c:55)
==30463== 
==30463== 856 bytes in 1 blocks are still reachable in loss record 25 of 61
==30463==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==30463==    by 0x10D2EB: env_to_str (env_to_str.c:23)
==30463==    by 0x10EDB3: exec_cmd (cmds.c:41)
==30463==    by 0x10D732: check_cmd (exec.c:71)
==30463==    by 0x10D667: check_pipe (exec.c:49)
==30463==    by 0x10D5EA: cmd_nb (exec.c:34)
==30463==    by 0x1094B9: loop (main.c:26)
==30463==    by 0x109552: init (main.c:48)
==30463==    by 0x10958C: main (main.c:55)
==30463== 
==30463== 6,496 bytes in 104 blocks are still reachable in loss record 47 of 61
==30463==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==30463==    by 0x110C98: ft_strjoin_free (ft_strjoin_free.c:48)
==30463==    by 0x10D4C1: add_env (env_to_str.c:66)
==30463==    by 0x10D34A: env_to_str (env_to_str.c:31)
==30463==    by 0x10EDB3: exec_cmd (cmds.c:41)
==30463==    by 0x10D732: check_cmd (exec.c:71)
==30463==    by 0x10D667: check_pipe (exec.c:49)
==30463==    by 0x10D5EA: cmd_nb (exec.c:34)
==30463==    by 0x1094B9: loop (main.c:26)
==30463==    by 0x109552: init (main.c:48)
==30463==    by 0x10958C: main (main.c:55)

Probably the env isn't free'd.

**Comment by MarcelCerdan** [comment]
FIXED
